export const API_BASE_URL = 'http://localhost:3000';

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_EMAIL: '/auth/verify-email',
    RESEND_VERIFICATION: '/auth/resend-verification',
    SSO_INITIATE: '/auth/sso/initiate',
  },
  USERS: {
    BASE: '/users',
    BY_ID: (id: string) => `/users/${id}`,
    ME: '/users/me',
    ME_PRESENCE: '/users/me/presence',
    PASSWORD: (id: string) => `/users/${id}/password`,
    AUDIT_LOGS: '/users/audit-logs',
  },
  TASKS: {
    BASE: '/tasks',
    BY_ID: (id: string) => `/tasks/${id}`,
    DETAILS: (id: string) => `/tasks/${id}/details`,
    STATUS: (id: string) => `/tasks/${id}/status`,
    ORDER: (id: string) => `/tasks/${id}/order`,
    ACTIVE: (id: string) => `/tasks/${id}/active`,
    REMINDERS_ME: '/tasks/reminders/me',
    REMINDERS_CREATE: (id: string) => `/tasks/${id}/reminders`,
    BATCH_UPDATE_ORDERS: '/tasks/batch-update-orders',
  },
  RECRUITMENT: {
    BASE: '/api/recruitment',
    PUBLIC_JOBS: '/api/recruitment/jobs',
    PUBLIC_APPLY: (jobOfferId: string) => `/api/recruitment/jobs/${jobOfferId}/apply`,
    TRACK_APPLICATION: (token: string) => `/api/recruitment/applications/track/${token}`,
    GENERATE: '/api/recruitment/generate',
    CHAT: '/api/recruitment/chat',
    LINKEDIN: '/api/recruitment/linkedin-post',
    COPILOT_HISTORY: '/api/recruitment/copilot/history',
    COPILOT_MESSAGE: '/api/recruitment/copilot/message',
    COPILOT_RESET: '/api/recruitment/copilot/reset',
    COPILOT_THREADS: '/api/recruitment/copilot/threads',
    COPILOT_THREAD: (threadId: string) => `/api/recruitment/copilot/threads/${threadId}`,
    COPILOT_THREAD_ARCHIVE: (threadId: string) => `/api/recruitment/copilot/threads/${threadId}/archive`,
    COPILOT_THREAD_MUTE: (threadId: string) => `/api/recruitment/copilot/threads/${threadId}/mute`,
    COPILOT_THREAD_DELETE: (threadId: string) => `/api/recruitment/copilot/threads/${threadId}/delete`,
    ADMIN_JOBS: '/api/recruitment/admin/jobs',
    ADMIN_JOB: (jobOfferId: string) => `/api/recruitment/admin/jobs/${jobOfferId}`,
    ADMIN_JOB_APPLICATIONS: (jobOfferId: string) => `/api/recruitment/admin/jobs/${jobOfferId}/applications`,
    ADMIN_JOB_PIPELINE: (jobOfferId: string) => `/api/recruitment/admin/jobs/${jobOfferId}/pipeline`,
    ADMIN_APPLICATION: (applicationId: string) => `/api/recruitment/admin/applications/${applicationId}`,
    ADMIN_APPLICATION_STATUS: (applicationId: string) => `/api/recruitment/admin/applications/${applicationId}/status`,
  },
  DASHBOARD: {
    ME: '/dashboard/me',
  },
  COLLABORATION: {
    BASE: '/collaboration',
    CONVERSATIONS: '/collaboration/conversations',
    ALL_CONVERSATIONS: '/collaboration/conversations',
    CONVERSATIONS_BY_USER: (userId: string) => `/collaboration/conversations/user/${userId}`,
    MESSAGES: (conversationId: string) => `/collaboration/conversations/${conversationId}/messages`,
    AI_DECOMPOSE: (conversationId: string) => `/collaboration/conversations/${conversationId}/ai-decompose`,
    APPROVE_PROPOSAL: (proposalId: string) => `/collaboration/proposals/${proposalId}/approve`,
    REJECT_PROPOSAL: (proposalId: string) => `/collaboration/proposals/${proposalId}/reject`,
  },
};
